# Form implementation generated from reading ui file 'Eyes-Track.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 614)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.faceFrame = QtWidgets.QLabel(parent=Form)
        self.faceFrame.setMouseTracking(False)
        self.faceFrame.setStyleSheet("border: 1px solid black;")
        self.faceFrame.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.faceFrame.setObjectName("faceFrame")
        self.gridLayout.addWidget(self.faceFrame, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.eyesImage = QtWidgets.QLabel(parent=Form)
        self.eyesImage.setStyleSheet("border: 1px solid black;")
        self.eyesImage.setObjectName("eyesImage")
        self.verticalLayout.addWidget(self.eyesImage)
        self.redComponent = QtWidgets.QLabel(parent=Form)
        self.redComponent.setStyleSheet("border: 1px solid black;")
        self.redComponent.setObjectName("redComponent")
        self.verticalLayout.addWidget(self.redComponent)
        self.hist = QtWidgets.QLabel(parent=Form)
        self.hist.setStyleSheet("border: 1px solid black;")
        self.hist.setObjectName("hist")
        self.verticalLayout.addWidget(self.hist)
        self.binary = QtWidgets.QLabel(parent=Form)
        self.binary.setStyleSheet("border: 1px solid black;")
        self.binary.setObjectName("binary")
        self.verticalLayout.addWidget(self.binary)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftEye = QtWidgets.QLabel(parent=Form)
        self.leftEye.setStyleSheet("border: 1px solid black;")
        self.leftEye.setObjectName("leftEye")
        self.horizontalLayout.addWidget(self.leftEye)
        self.rightEye = QtWidgets.QLabel(parent=Form)
        self.rightEye.setStyleSheet("border: 1px solid black;")
        self.rightEye.setObjectName("rightEye")
        self.horizontalLayout.addWidget(self.rightEye)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startCamera = QtWidgets.QPushButton(parent=Form)
        self.startCamera.setObjectName("startCamera")
        self.horizontalLayout_3.addWidget(self.startCamera)
        self.openFile = QtWidgets.QPushButton(parent=Form)
        self.openFile.setObjectName("openFile")
        self.horizontalLayout_3.addWidget(self.openFile)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 2, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(parent=Form)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.verticalSlider, 0, 0, 1, 1)
        self.test = QtWidgets.QPushButton(parent=Form)
        self.test.setObjectName("test")
        self.gridLayout.addWidget(self.test, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.faceFrame.setText(_translate("Form", "faceFrame"))
        self.eyesImage.setText(_translate("Form", "eyesImage"))
        self.redComponent.setText(_translate("Form", "redComponent"))
        self.hist.setText(_translate("Form", "hist"))
        self.binary.setText(_translate("Form", "binary"))
        self.leftEye.setText(_translate("Form", "leftEye"))
        self.rightEye.setText(_translate("Form", "rightEye"))
        self.startCamera.setText(_translate("Form", "startCamera"))
        self.openFile.setText(_translate("Form", "openFile"))
        self.test.setText(_translate("Form", "test"))
