# Form implementation generated from reading ui file 'Eyes-Track.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 590)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.startCamera = QtWidgets.QPushButton(parent=Form)
        self.startCamera.setObjectName("startCamera")
        self.gridLayout.addWidget(self.startCamera, 1, 2, 1, 1)
        self.faceFrame = QtWidgets.QLabel(parent=Form)
        self.faceFrame.setMouseTracking(False)
        self.faceFrame.setStyleSheet("border: 1px solid black;")
        self.faceFrame.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.faceFrame.setObjectName("faceFrame")
        self.gridLayout.addWidget(self.faceFrame, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setStyleSheet("border: 1px solid black;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setStyleSheet("border: 1px solid black;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setStyleSheet("border: 1px solid black;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftEye = QtWidgets.QLabel(parent=Form)
        self.leftEye.setStyleSheet("border: 1px solid black;")
        self.leftEye.setObjectName("leftEye")
        self.horizontalLayout.addWidget(self.leftEye)
        self.rightEye = QtWidgets.QLabel(parent=Form)
        self.rightEye.setStyleSheet("border: 1px solid black;")
        self.rightEye.setObjectName("rightEye")
        self.horizontalLayout.addWidget(self.rightEye)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(parent=Form)
        self.verticalSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.verticalSlider, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.startCamera.setText(_translate("Form", "startCamera"))
        self.faceFrame.setText(_translate("Form", "faceFrame"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.leftEye.setText(_translate("Form", "leftEye"))
        self.rightEye.setText(_translate("Form", "rightEye"))
